pool:
  vmImage: ubuntu-16.04
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven Springboot/pom.xml'
  inputs:
    mavenPomFile: Springboot/pom.xml

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: sidda
    repository: siddareddy/test
    Dockerfile: Springboot/Dockerfile

- task: HelmInstaller@0
  displayName: 'Install Helm 3.0.0'
  inputs:
    helmVersion: 3.0.0
    checkLatestHelmVersion: false
    
- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    azureSubscription: azure
    azureResourceGroup: 'aaa-sidda-rg'
    kubernetesCluster: 'aks-cluster94f0'
    namespace: demo
    command: package
    chartPath: 'spring-helm'
    save: false
    arguments: '--set image.tag=$(Build.BuildId)'   
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


steps:
- task: HelmInstaller@0
  displayName: 'Install Helm 3.0.0'
  inputs:
    helmVersion: 3.0.0
    
- task: HelmDeploy@0
  displayName: 'helm install'
  inputs:
    azureSubscription: azure
    azureResourceGroup: 'aaa-sidda-rg'
    kubernetesCluster: 'aks-cluster94f0'
    namespace: demo
    command: install
    chartType: FilePath
    chartPath: '$(System.DefaultWorkingDirectory)/_AKS-build/drop/spring-0.1.0.tgz'
    releaseName: springapps
