# Default values for mfpro-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Generic properties
namespace: demo
replicaCount: 1
ingressEnabled: true
appName: my-boot-service
containerPort: 8080

# Images
image:
  repository: siddareddy/test
  tag: 45
  pullPolicy: Always
ingress:
  enabled: true
  name: my-boot-service
  rules:
    - host: my-boot-service
      http:
        paths:
        - path: /api/auth
          backend:
            serviceName: my-boot-service-entrypoint
            servicePort: 80