apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-entrypoint
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3423
      targetPort: {{ .Values.containerPort }}
      name: http